- ark_sdk_python/cli_services/ark_cli_api.py
- ark_sdk_python/services/dpa/ark_dpa_api.py
> ARK-600: Minor fixes to missing API's

- ark_sdk_python/common/ark_keyring.py
> ARK-600: Keyring fallback last resort

- .github/workflows/build.yml
> Tag exists do not fail

- .github/workflows/build.yml
- ark_sdk_python/services/sm/ark_sm_service.py
- poetry.lock
> Fixes and poetry update

- ark_sdk_python/models/services/dpa/sso/ark_dpa_sso_get_short_lived_client_certificate.py
- ark_sdk_python/models/services/dpa/sso/ark_dpa_sso_get_short_lived_rdp_file.py
- ark_sdk_python/services/dpa/sso/ark_dpa_sso_service.py
- poetry.lock
- pyproject.toml
> Fixed RDP file not accepting target user

- ark_sdk_python/actions/ark_configure_action.py
- ark_sdk_python/args/ark_pydantic_argparse.py
- ark_sdk_python/common/isp/ark_isp_service_client.py
- ark_sdk_python/models/services/dpa/sso/__init__.py
- ark_sdk_python/models/services/dpa/sso/ark_dpa_sso_get_short_lived_client_certificate.py
- ark_sdk_python/models/services/dpa/sso/ark_dpa_sso_get_short_lived_oracle_wallet.py
- ark_sdk_python/models/services/dpa/workspaces/db/ark_dpa_db_add_database.py
- ark_sdk_python/models/services/dpa/workspaces/db/ark_dpa_db_database.py
- ark_sdk_python/models/services/dpa/workspaces/db/ark_dpa_db_update_database.py
- ark_sdk_python/services/dpa/sso/ark_dpa_sso_service.py
- poetry.lock
- pyproject.toml
> Client cert and oracle wallet SSO additional params

- LICENSE.txt
- ark_sdk_python/models/services/dpa/policies/db/ark_dpa_db_connection_data.py
- ark_sdk_python/models/services/dpa/workspaces/db/ark_dpa_db_provider.py
- docs/license.md
- pyproject.toml
> Support DB2 and minor extra fixes

- ark_sdk_python/actions/ark_login_action.py
- ark_sdk_python/auth/ark_isp_auth.py
- ark_sdk_python/auth/identity/ark_identity.py
- ark_sdk_python/models/actions/ark_configure_action_consts.py
- ark_sdk_python/models/auth/ark_auth_method.py
- pyproject.toml
- tests/unit/auth/test_ark_isp_auth.py
> Fixed an issue where the idp user check was not taking the identity url into account, also added subdomain optional param for discovery

- docs/examples/sdk_examples.md
> Identity service support, containing Users, Roles, Policies and Directories API's with fitting validation models

- ark_sdk_python/models/services/dpa/policies/db/ark_dpa_db_connection_data.py
- ark_sdk_python/models/services/dpa/policies/db/ark_dpa_db_enums.py
- ark_sdk_python/models/services/dpa/secrets/db/ark_dpa_db_secret_type.py
- ark_sdk_python/models/services/dpa/secrets/db/secrets_data/__init__.py
- ark_sdk_python/models/services/dpa/secrets/db/secrets_data/ark_dpa_db_iam_user_secret_data.py
- ark_sdk_python/models/services/dpa/workspaces/db/__init__.py
- ark_sdk_python/models/services/dpa/workspaces/db/ark_dpa_db_add_database.py
- ark_sdk_python/models/services/dpa/workspaces/db/ark_dpa_db_auth_method.py
- ark_sdk_python/models/services/dpa/workspaces/db/ark_dpa_db_database.py
- ark_sdk_python/models/services/dpa/workspaces/db/ark_dpa_db_database_info.py
- ark_sdk_python/models/services/dpa/workspaces/db/ark_dpa_db_databases_filter.py
- ark_sdk_python/models/services/dpa/workspaces/db/ark_dpa_db_databases_stats.py
- ark_sdk_python/models/services/dpa/workspaces/db/ark_dpa_db_update_database.py
- ark_sdk_python/models/services/identity/roles/ark_identity_admin_right.py
- ark_sdk_python/services/dpa/workspaces/db/ark_dpa_db_workspace_service.py
- pyproject.toml
> DB Auth Method + extra admin rights

- ark_sdk_python/models/services/dpa/secrets/db/ark_dpa_db_add_secret.py
- ark_sdk_python/models/services/dpa/secrets/db/ark_dpa_db_update_secret.py
- ark_sdk_python/models/services/dpa/workspaces/db/ark_dpa_db_auth_method.py
- ark_sdk_python/services/dpa/secrets/db/ark_dpa_db_secrets_service.py
- pyproject.toml
> IAM User secret support

- ark_sdk_python/auth/identity/ark_identity.py
- ark_sdk_python/common/env/__init__.py
- ark_sdk_python/common/env/ark_env_mapping.py
- ark_sdk_python/models/services/dpa/secrets/db/ark_dpa_db_add_secret.py
- ark_sdk_python/models/services/dpa/secrets/db/ark_dpa_db_secret_type.py
- ark_sdk_python/models/services/dpa/secrets/db/ark_dpa_db_store_type.py
- ark_sdk_python/models/services/dpa/secrets/db/ark_dpa_db_update_secret.py
- ark_sdk_python/models/services/dpa/secrets/db/secrets_data/__init__.py
- ark_sdk_python/models/services/dpa/secrets/db/secrets_data/ark_dpa_db_atlas_access_keys_secret_data.py
- ark_sdk_python/models/services/dpa/workspaces/db/ark_dpa_db_add_database.py
- ark_sdk_python/models/services/dpa/workspaces/db/ark_dpa_db_database.py
- ark_sdk_python/models/services/dpa/workspaces/db/ark_dpa_db_update_database.py
- ark_sdk_python/services/dpa/secrets/db/ark_dpa_db_secrets_service.py
- ark_sdk_python/services/dpa/workspaces/db/ark_dpa_db_workspace_service.py
- ark_sdk_python/services/identity/common/ark_identity_base_service.py
- pyproject.toml
> Atlas support and alignments

- ark_sdk_python/models/auth/ark_auth_method.py
- pyproject.toml
- tests/unit/auth/test_ark_isp_auth.py
> App name fix

- ark_sdk_python/common/ark_jwt_utils.py
- ark_sdk_python/common/connections/ssh/__init__.py
- ark_sdk_python/common/connections/ssh/ark_pty_ssh_connection.py
- ark_sdk_python/examples/validate_ssh_connection.py
- docs/examples/commands_examples.md
- docs/howto/install_sia_connectors.md
- mkdocs.yml
- poetry.lock
- pyproject.toml
> Validate SSH Example + Extra documentation

- ark_sdk_python/auth/identity/ark_identity.py
- pyproject.toml
> Save cookies for re-use when using the last start auth response

- NOTICES.md
- pyproject.toml
> Win PTY implementation for ssh connections in windows

- ark_sdk_python/auth/identity/ark_identity.py
- pyproject.toml
> OTP and OATH

- ark_sdk_python/auth/identity/ark_identity.py
- ark_sdk_python/models/auth/ark_auth_method.py
- pyproject.toml
> adding oath to settings

- ark_sdk_python/models/services/pcloud/safes/ark_pcloud_safe.py
- pyproject.toml
> Fix typing on retention on safes

- README.md
- ark_sdk_python/ark_api.py
- ark_sdk_python/auth/identity/ark_identity_service_user.py
- ark_sdk_python/models/actions/services/ark_sia_exec_action_consts.py
- ark_sdk_python/models/services/sia/ssh_ca/__init__.py
- ark_sdk_python/models/services/sia/ssh_ca/ark_sia_get_ssh_public_key.py
- ark_sdk_python/models/services/sia/sso/ark_sia_sso_get_short_lived_password.py
- ark_sdk_python/services/sia/ark_sia_api.py
- ark_sdk_python/services/sia/ssh_ca/__init__.py
- ark_sdk_python/services/sia/ssh_ca/ark_sia_ssh_ca_service.py
- ark_sdk_python/services/sia/sso/ark_sia_sso_service.py
- docs/commands/exec.md
- docs/examples/commands_examples.md
- docs/howto/enduser_rdp_workflow.md
- docs/sdk/services.md
- poetry.lock
- pyproject.toml
> Add RDP MFA Caching Password and SSH CA Support
